"""Helpers shared by V2 tests: FFprobe inspection and sample media."""

import json
import shutil
import subprocess
from pathlib import Path

import pytest

FFMPEG = shutil.which("ffmpeg")
FFPROBE = shutil.which("ffprobe")


def ffprobe_streams(media_path: Path) -> dict:
    """Return ffprobe streams + format info for ``media_path``."""
    command = [
        FFPROBE,
        "-v",
        "error",
        "-show_streams",
        "-show_format",
        "-of",
        "json",
        str(media_path),
    ]
    result = subprocess.run(command, check=True, capture_output=True, text=True)
    return json.loads(result.stdout)


def first_stream(probe: dict, codec_type: str) -> dict:
    for stream in probe.get("streams", []):
        if stream.get("codec_type") == codec_type:
            return stream
    raise AssertionError(f"no {codec_type} stream found")


def video_stream(media_path: Path) -> dict:
    return first_stream(ffprobe_streams(media_path), "video")


def audio_stream(media_path: Path) -> dict:
    return first_stream(ffprobe_streams(media_path), "audio")


@pytest.fixture(scope="session")
def sample_video(tmp_path_factory) -> Path:
    """A tiny H.264 MP4 (640x360, ~2s, with audio) generated by FFmpeg."""
    if FFMPEG is None:
        pytest.skip("ffmpeg not available")

    output = tmp_path_factory.mktemp("samples") / "sample.mp4"
    command = [
        FFMPEG,
        "-y",
        "-f",
        "lavfi",
        "-i",
        "color=c=black:s=640x360:d=2:r=25",
        "-f",
        "lavfi",
        "-i",
        "sine=frequency=440:duration=2",
        "-c:v",
        "libx264",
        "-preset",
        "ultrafast",
        "-c:a",
        "aac",
        "-shortest",
        str(output),
    ]
    subprocess.run(command, check=True, capture_output=True)
    return output


def video_id_to_layout(tmp_path):
    from v2.media.layout import build_layout

    return build_layout("test-vid", data_dir=tmp_path)